import { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { ArrowUpRight, Compass } from 'lucide-react';
import type { Activity } from '../types';

export default function IdeaOrbit({ items, onSelect, reduced }: { items:Activity[];onSelect:(a:Activity)=>void;reduced:boolean }) {
 const [activeId,setActiveId]=useState(items[0]?.id);
 const selected=items.find(a=>a.id===activeId)||items[0];
 const visible=items.slice(0,12);
 useEffect(()=>{if(!items.some(a=>a.id===activeId))setActiveId(items[0]?.id);},[items,activeId]);
 if(!selected)return <div className="orbit-empty"><Compass size={36}/><p>No matches in this orbit. Widen your filters to find a spark.</p></div>;
 return <div className="orbit-browser"><div className="orbit-chart"><svg viewBox="0 0 600 430" role="group" aria-label="Idea constellation. A visual way to browse ideas, not a geographic map."><defs><radialGradient id="orbit-halo"><stop offset="0" stopColor="#d2ff8c" stopOpacity=".12"/><stop offset="1" stopColor="#d2ff8c" stopOpacity="0"/></radialGradient></defs><circle cx="300" cy="215" r="180" fill="url(#orbit-halo)"/>{[65,120,178].map(radius=><circle key={radius} className="range-circle" cx="300" cy="215" r={radius}/>)}<path className="crosshair" d="M70 215H530M300 20V410"/><circle cx="300" cy="215" r="24" fill="#c9ff8e0f" stroke="#b6ee7a4a"/><text x="300" y="219" textAnchor="middle" style={{fill:'#d2ff8c',fontSize:11,letterSpacing:2}}>YOU</text>{visible.map((item,index)=>{const angle=(index/visible.length)*Math.PI*2-Math.PI/2,radius=index%3===0?115:177;const x=300+Math.cos(angle)*radius,y=215+Math.sin(angle)*radius;return <motion.g key={item.id} className="orbit-node" role="button" tabIndex={0} aria-label={`Explore ${item.title}`} aria-pressed={selected.id===item.id} onFocus={()=>setActiveId(item.id)} onMouseEnter={()=>setActiveId(item.id)} onClick={()=>setActiveId(item.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActiveId(item.id);onSelect(item);}}} initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{delay:index*.05}}><line x1="300" y1="215" x2={x} y2={y} stroke={selected.id===item.id?'#b6e77d60':'#829d621c'}/>{selected.id===item.id&&<motion.circle cx={x} cy={y} r="21" fill="none" stroke="#d2ff8c30" animate={reduced?{}:{r:[15,30],opacity:[.7,0]}} transition={{duration:2,repeat:Infinity}}/>}<circle cx={x} cy={y} r={selected.id===item.id?8:5}/><text x={x} y={y+24} textAnchor="middle">{item.title.length>23?item.title.slice(0,21)+'…':item.title}</text></motion.g>;})}<text x="25" y="28" style={{fontSize:8,letterSpacing:1.8}}>POSSIBILITIES / {String(visible.length).padStart(2,'0')}</text><text x="25" y="405" style={{fontSize:8,letterSpacing:1.3}}>IDEA CONSTELLATION · NOT A MAP</text></svg></div><div className="orbit-list"><span className="eyebrow">FOLLOW A SPARK <span>↗</span></span><motion.div key={selected.id} initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:.3}}><h3>{selected.title}</h3><p>{selected.description}</p><button className="dark-button" onClick={()=>onSelect(selected)}>Explore this idea<ArrowUpRight size={17}/></button></motion.div><small>Tap a spark to find a different kind of day.</small></div></div>;
}
