import type { Activity, Filters } from './types';
const asset = (name: string) => `${import.meta.env.BASE_URL}images/${name}`;
export const photos = { coast: asset('coast.jpg'), dining: asset('dining.jpg'), event: asset('event.jpg') };
export const initialFilters: Filters = { category: 'all', mood: 'anything', radius: 25, budget: 200, dining: 'any', date: 'any', newOnly: false, indoor: 'any', accessible: false, query: '' };
export const ideas: Activity[] = [
 { id:'idea-sunset',title:'Chase the last light',category:'outdoors',description:'Find a waterfront trail, pack a little picnic, and stay for the sunset. Sometimes the best plan is the simplest one.',image:photos.coast,moods:['romantic','chill','family'],price:0,duration:'1–2 hours',source:'Outing idea',inspiration:true,indoor:false },
 { id:'idea-dinner',title:'A table for two. Somewhere new.',category:'food',description:'Trade your usual spot for a cozy neighborhood restaurant. Pick a dish you have never tried and make an evening of it.',image:photos.dining,moods:['romantic','chill'],duration:'1–2 hours',source:'Outing idea',inspiration:true,dining:['sitdown'],indoor:true },
 { id:'idea-music',title:'Find your next favorite live act',category:'events',description:'Small stages, big memories. Explore upcoming local shows and outdoor concerts, and check the organizer for times and tickets.',image:photos.event,moods:['fun','romantic','adventurous'],duration:'2–3 hours',source:'Outing idea',inspiration:true },
 { id:'idea-beach',title:'An out-of-office kind of day',category:'daytrip',description:'Take the scenic route to the coast. Bring a towel, something to read, and absolutely no ambitious agenda.',image:photos.coast,moods:['chill','family','adventurous'],duration:'Half a day',source:'Outing idea',inspiration:true,indoor:false },
 { id:'idea-takeout',title:'Takeout with a better view',category:'food',description:'Pick up something delicious and find a picnic-friendly park. All the good food, a little more fresh air.',image:photos.dining,moods:['fun','chill','family','romantic'],duration:'1 hour',source:'Outing idea',inspiration:true,dining:['takeout'],indoor:false },
 { id:'idea-market',title:'Make a morning of the market',category:'events',description:'A local market is a good excuse to slow down. Browse seasonal produce, meet the makers, and find a new favorite snack.',image:photos.event,moods:['family','fun','chill'],duration:'1–2 hours',source:'Outing idea',inspiration:true,indoor:false },
 { id:'idea-museum',title:'Get a little lost in an art museum',category:'culture',description:'Follow your curiosity through a gallery or museum. Choose one piece each, then talk about it over coffee.',image:photos.dining,moods:['romantic','chill','family'],duration:'2 hours',source:'Outing idea',inspiration:true,indoor:true },
 { id:'idea-hike',title:'The trail you haven’t taken',category:'outdoors',description:'Pick a new walking trail, fill your water bottle, and put your phone away for a while. Check trail conditions before setting off.',image:photos.coast,moods:['adventurous','fun','family'],price:0,duration:'2–3 hours',source:'Outing idea',inspiration:true,indoor:false },
 { id:'idea-game',title:'A little friendly competition',category:'culture',description:'Try bowling, an arcade, an escape room, or mini golf. Winner picks where you eat afterward.',image:photos.event,moods:['fun','family','adventurous'],duration:'1–2 hours',source:'Outing idea',inspiration:true,indoor:true },
 { id:'idea-coffee',title:'The slow Sunday coffee crawl',category:'food',description:'Find an independent café, order their signature drink, and claim a sunny seat. Bring a friend or a good book.',image:photos.dining,moods:['chill','romantic'],duration:'1 hour',source:'Outing idea',inspiration:true,dining:['sitdown','takeout'],indoor:true }
];

